title = "Health Sciences Journal"
baseURL = "https://tranquil-salmiakki-4ddf0d.netlify.app/"
languageCode = "en-US"


# The site's parameters
[params]
  home = "Home"
  abbreviatedTitle = "Health Sci. J. Theme"
  description = "The Health Sciences Journal aims to inform about current health news and interesting facts about the topic"
  favicon = "img/favicon.png"
  mirrorfor = ""
  eISSN = "XXXX-XXXX"
  printISSN = "XXXX-XXXX"

  ## CUSTOM THEME COLOURS
  ### Main three colours to change. If parameters not set, default colours will be applied.
  ## primaryColour = "#10beca"
  ## linkColour = "#0a7b83"
  ## badgeBackgroundColour = "#b8eff3"

  ### Additional colours that don't change often
  ## alertDangerBackgroundColour = "#ca1031"
  ## alertColour = "#000"
  ## alertDangerColour = "#fff"
  ## bodyColour = "#333"
  ## buttonBorderColour = "#757575"
  ## buttonLightColour = "#f7f7f7"
  ## pageItemBorderColour = "#ddd"
    
  ## Publisher Information
  publisher = {name = "Episteme Health Inc.", city = "Melbourne", state = "Victoria", country = "Australia"}
  journalDOI = "10.xxxx/demo"
  publisherjournalabbreviation = "HSJT"
  subjects = ["Subject1", "Subject2"]
  crossmark_enabled = false
  
  ## Homepage image. Different sizes can be used to provide responsiveness.
  homepageimageset = [{img = "img/homepage_480w.jpg", width = "480w", maxwidth = "800px"},
    {img = "img/homepage_960w.jpg", width = "960w", maxwidth = "1440px"},
    {img = "img/homepage_1920w.jpg", width = "1920w", maxwidth = ""}]
  homepageimagefallback = "img/homepage_960w.jpg"
  homepageimagealt = "Neurons artwork homepage image. CC0 Geralt/Pixabay id-582054"
  
  lenslogo = "img/lens-journal-logo.png"
  
  ## Set current issue or leave blank and the most recent issue will be used.
  currentissuepath = ""
  
  twittercard = "summary_large_image"
  twitterhandle = "@epistemehealth"
  socialimage = "img/twittercard.jpg"
  socialimagealt = "Health Sciences Journal Logo"
  socialdescription = "Health Sciences Journal Description"
  
  ## Set to true to load libraries from Cloudflare and Bootstrap CDNs where available. Otherwise leave blank.
  useCDN = false
  
  ## Custom blocks for the footer
  customblocks = [{ name = "Custom Block", content = "Website footer custom block."},
  {name = "License", content = "This theme is adapted from the [Health Sciences Theme](https://github.com/pkp/healthsciences) by the Public Knowledge Project under a GPL license. It is released under a GPL3 license."},
  {name = "Privacy Notice", content = "The only user information collected from this website is in the form of log files generated the site's [hosting provider](https://www.netlify.com/privacy/)."},
  {name = "Contact Us", content = "Web created by [Maria Jose R.U](https://www.instagram.com/womenshealthmag/), at [Woman´s Health](https://likeshop.me/womenshealthmag)."}]
  
  footercontent = "Footer content."
  
  
  [privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.disqus]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
  
  [menu]

    [[menu.main]]
      weight = 2
      name = "Nutrition"
      url = "about/nutrition"
    [[menu.main]]
      weight = 3
      name = "Health Tools"
      url = "about/tools"
    [[menu.main]]
      weight = 4
      name = "Newsletter"
      url = "about/submissions"
    [[menu.main]]
      weight = 5
      name = "About"
      hasChildren = true
    [[menu.main]]
      parent = "About"
      name = "Podcast"
      url = "about/podcast"
      weight = 6
    [[menu.main]]
      parent = "About"
      name = "Medical Myths"
      url = "about/myths"
      weight = 7
    [[menu.main]]
      parent = "About"
      name = "Latest News"
      url = "about/lnews"
      weight = 8

# Output formats
[mediaTypes]
  [mediaTypes."text/ris"]
    suffixes = ["ris"]
  [mediaTypes."text/bib"]
    suffixes = ["bib"]
  [mediaTypes."text/enw"]
    suffixes = ["enw"]
  [mediaTypes."text/latex"]
    suffixes = ["tex"]
    
[outputFormats]
  [outputFormats.galleyPDF]
    baseName = "view-pdf"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.galleyXML]
    baseName = "view-lens"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.galleyHTML]
    baseName = "view-html"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.customlens]
    baseName = "js/customlens"
    isPlainText = true
    mediaType = "application/javascript"
    path = ""
  [outputFormats.defaultcss]
    baseName = "css/default"
    isPlainText = true
    mediaType = "text/css"
    path = ""
  [outputFormats.localfonts]
    baseName = "css/localfonts"
    isPlainText = true
    mediaType = "text/css"
    path = ""
  [outputFormats.lensfonts]
    baseName = "css/lensfonts"
    isPlainText = true
    mediaType = "text/css"
    path = ""
  [outputFormats.htmlgalleyfonts]
    baseName = "css/htmlgalleyfonts"
    isPlainText = true
    mediaType = "text/css"
    path = ""
  [outputFormats.exportris]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/ris"
    path = ""
  [outputFormats.exportbib]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/bib"
    path = ""
  [outputFormats.exportenw]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/enw"
    path = ""
  [outputFormats.exportcsljson]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "application/json"
    path = ""

[outputs]
  home = ["HTML", "customlens", "defaultcss", "localfonts", "lensfonts", "htmlgalleyfonts"]
  page = ["html", "galleyPDF", "galleyXML", "galleyHTML", "exportris", "exportenw", "exportbib", "exportcsljson" ]

[taxonomies]
  keyword = "keywords"